// Copyright 2018 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import * as vscode from "vscode";

import { BazelWorkspaceInfo } from "../bazel";
import { getTargetsForBuildFile } from "../bazel";
import { getDefaultBazelExecutablePath } from "../extension/configuration";
import { CodeLensBuilder } from "./code_lens_builder";

/**
 * Provides CodeLenses for targets in Bazel BUILD files.
 * Responsible for querying Bazel for target information and creating actionable CodeLens items.
 *
 * Features:
 * - Queries Bazel for target information
 * - Creates actionable CodeLens items for build/run/test operations
 * - Handles dirty file states to prevent stale information
 */
export class CodeLensProvider implements vscode.CodeLensProvider {
  public onDidChangeCodeLenses: vscode.Event<void>;
  private onDidChangeCodeLensesEmitter = new vscode.EventEmitter<void>();
  private builder: CodeLensBuilder;

  /**
   * Initializes a new CodeLens provider.
   */
  constructor() {
    this.onDidChangeCodeLenses = this.onDidChangeCodeLensesEmitter.event;
    this.builder = new CodeLensBuilder();
  }

  /**
   * Refreshes all CodeLens items by emitting a change event.
   */
  public refresh(): void {
    this.onDidChangeCodeLensesEmitter.fire();
  }

  /**
   * Provides promisified CodeLen(s) for the given document.
   *
   * @param document A Bazel BUILD file
   * @param token CodeLens token automatically generated by VS Code when
   * invoking the provider
   */
  public async provideCodeLenses(
    document: vscode.TextDocument,
  ): Promise<vscode.CodeLens[]> {
    if (document.isDirty) {
      // Don't show code lenses for dirty BUILD files; we can't reliably
      // determine what the build targets in it are until it is saved and we can
      // invoke `bazel query` with the updated file.
      return [];
    }

    const workspaceInfo = BazelWorkspaceInfo.fromDocument(document);
    if (workspaceInfo === undefined) {
      // Not in a Bazel Workspace.
      return [];
    }

    const queryResult = await getTargetsForBuildFile(
      getDefaultBazelExecutablePath(),
      workspaceInfo.bazelWorkspacePath,
      document.uri.fsPath,
    ).catch((error) => {
      // eslint-disable-next-line no-console
      console.error("Error getting targets for build file:", error);
      return undefined;
    });

    if (queryResult === undefined) {
      return [];
    }

    return this.builder.buildCodeLenses(workspaceInfo, queryResult);
  }
}
