# Note this file contains different kinds of labels on purpose - used by copy_label_to_clipboard test
# Empty line
filegroup(
    name = "foobar",
    srcs = ["subfolder/foobar.txt"],
    data = glob(
        [
            "subfolder/*.txt",
            "mydata.txt",
        ],
    ),
)
# EOF
