#!/usr/bin/env bash

# Copyright 2018 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

# Move into the top-level directory of the project.
cd "$(dirname "${BASH_SOURCE[0]}")/.." > /dev/null

while IFS= read -r path; do
  directory="$(dirname "src/protos/$path")"
  filename="$(basename "$path")"
  name="${filename/.proto/_proto}"
  mkdir -p "$directory"
  curl -L \
      "https://raw.githubusercontent.com/bazelbuild/bazel/master/$path" \
      > "src/protos/$path"
  echo -e "load('@rules_proto//proto:defs.bzl', 'proto_library')\nproto_library(name='$name')" | buildifier -type build > "$directory/BUILD"
done < src/protos/protos_list.txt

# Remove the files generated by build.sh to force them to be regenerated.
rm -f src/protos/protos.js
rm -f src/protos/protos.d.ts
